# goal
std_msgs/Header header
capabilities2_msgs/CapabilityCommand goal
---
# result
std_msgs/Header header
capabilities2_msgs/CapabilityResponse result
---
# feedback
std_msgs/Header header
capabilities2_msgs/Capability capability
int32 progress
capabilities2_msgs/Remapping[] state
