/**:
  ros__parameters:
    loop_rate: 5.0 # Hz
    db_file: ~/cache/capabilities.sqlite3
    rebuild: false # Set to true to rebuild the database
    package_paths: # paths to search for capabilities
      - /opt/ros
