fabric_client:
  ros__parameters:
    plan_file_path: "install/capabilities2_fabric/share/capabilities2_fabric/plans/prompt_4.xml"     # PromptPlanRunner Example
    # plan_file_path: "install/capabilities2_fabric/share/capabilities2_fabric/plans/prompt_3.xml"     # PromptPoseRunner Example
    # plan_file_path: "install/capabilities2_fabric/share/capabilities2_fabric/plans/prompt_2.xml"     # PromptOccupancyRunner Example
    # plan_file_path: "install/capabilities2_fabric/share/capabilities2_fabric/plans/prompt_1.xml"     # PromptCapabilityRunner Example
    # plan_file_path: "install/capabilities2_fabric/share/capabilities2_fabric/plans/navigation_2.xml" # WaypointRunner Example 2
    # plan_file_path: "install/capabilities2_fabric/share/capabilities2_fabric/plans/navigation_1.xml" # WaypointRunner Example 1
    # plan_file_path: "install/capabilities2_fabric/share/capabilities2_fabric/plans/default.xml"
