capabilities2_file_parser:
  ros__parameters:
    plan_file_path: "install/capabilities2_fabric/share/capabilities2_fabric/plans/navigation_1.xml" # WaypointRunner Example 1
    # plan_file_path: "install/capabilities2_fabric/share/capabilities2_fabric/plans/default.xml" 
