<?xml version="1.0"?>
<package format="3">
  <name>capabilities2_events</name>
  <version>0.2.0</version>
  <description>
    Event subsystem for the capabilities2 framework
  </description>

  <maintainer email="michael.pritchard@canberra.edu.au">Michael Pritchard</maintainer>
  <maintainer email="kalana.ratnayakemudiyanselage@canberra.edu.au">Kalana Ratnayake</maintainer>

  <author email="michael.pritchard@canberra.edu.au">Michael Pritchard</author>
  <author email="kalana.ratnayakemudiyanselage@canberra.edu.au">Kalana Ratnayake</author>

  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>capabilities2_msgs</depend>
  <depend>uuid</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
